let products = window.DonnaCatalog.load();
const money=value=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(value);
const $=selector=>document.querySelector(selector),productGrid=$('#productGrid');
const imageSrc=image=>/^data:image\//i.test(String(image||''))?image:`assets/${image}`;
const safeText=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
let activeCategory='Todos',searchTerm='',sortMode='featured',detailProduct=null,selectedSize='M',shippingFee=null,quotedAddress=null;
let cart=readStorage('donna-cart',[]),favorites=readStorage('donna-favorites',[]);
function readStorage(key,fallback){try{return JSON.parse(localStorage.getItem(key))??fallback}catch{return fallback}}
function saveStorage(){try{localStorage.setItem('donna-cart',JSON.stringify(cart));localStorage.setItem('donna-favorites',JSON.stringify(favorites))}catch{}}
function toast(message){const el=$('#toast');el.textContent=message;el.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.classList.remove('show'),2200)}
function renderCategoryTabs(){const tabs=$('#categoryTabs');if(!tabs)return;const categories=[...new Set(products.map(product=>product.category).filter(Boolean))];if(activeCategory!=='Todos'&&activeCategory!=='Favoritos'&&!categories.includes(activeCategory))activeCategory='Todos';const buttons=[`<button class="category-tab ${activeCategory==='Todos'?'active':''}" data-category="Todos">Tudo <span>${products.length}</span></button>`,...categories.map(category=>`<button class="category-tab ${activeCategory===category?'active':''}" data-category="${category}">${category}</button>`),`<button class="category-tab ${activeCategory==='Favoritos'?'active':''}" data-category="Favoritos">♡ Favoritos</button>`];tabs.innerHTML=buttons.join('')}
function renderProducts(){renderCategoryTabs();let list=products.filter(p=>(activeCategory==='Todos'||(activeCategory==='Favoritos'?favorites.includes(p.id):p.category===activeCategory))&&(!searchTerm||`${p.name} ${p.category}`.toLowerCase().includes(searchTerm.toLowerCase())));if(sortMode==='price-asc')list.sort((a,b)=>a.price-b.price);if(sortMode==='price-desc')list.sort((a,b)=>b.price-a.price);if(sortMode==='name')list.sort((a,b)=>a.name.localeCompare(b.name,'pt-BR'));if(!list.length){productGrid.innerHTML='<div class="no-results"><b>Nenhuma peça por aqui</b>Tente outro nome ou escolha uma categoria diferente.</div>';return}productGrid.innerHTML=list.map((p,i)=>`<article class="product-card" style="animation-delay:${Math.min(i,8)*45}ms" data-product="${p.id}"><div class="product-media"><img loading="lazy" src="${imageSrc(p.image)}" alt="${safeText(p.name)}"/><span class="product-label">${safeText(p.tag||'Donna Maria')}</span><button class="product-heart ${favorites.includes(p.id)?'is-favorite':''}" data-favorite="${p.id}" aria-label="${favorites.includes(p.id)?'Remover dos':'Adicionar aos'} favoritos"><svg viewBox="0 0 24 24"><path d="M20.8 8.9c0 5.3-8.8 11-8.8 11s-8.8-5.7-8.8-11A4.7 4.7 0 0 1 12 6.6a4.7 4.7 0 0 1 8.8 2.3Z"/></svg></button><button class="quick-add" data-detail="${p.id}">Ver peça e tamanhos&nbsp; ↗</button></div><div class="product-info"><div class="product-category">${safeText(p.category)}</div><h3 class="product-title">${safeText(p.name)}</h3><div class="product-price">${money(p.price)} ${p.old?`<del>${money(p.old)}</del>`:''}</div><div class="product-installments">Confira condições de pagamento</div></div></article>`).join('')}
function setCategory(category){activeCategory=category;document.querySelectorAll('.category-tab').forEach(t=>t.classList.toggle('active',t.dataset.category===category));renderProducts();$('#activeFilters').innerHTML=category==='Todos'?'':`<button class="clear-filter">${category} <span>×</span></button>`}
function toggleFavorite(id){favorites=favorites.includes(id)?favorites.filter(x=>x!==id):[...favorites,id];saveStorage();renderProducts();toast(favorites.includes(id)?'Adicionado aos favoritos ♡':'Removido dos favoritos')}
function showProduct(id){detailProduct=products.find(p=>p.id===id);if(!detailProduct)return;selectedSize=(detailProduct.sizes||[]).includes('M')?'M':(detailProduct.sizes||[])[0]||'Único';$('#detailImage').src=imageSrc(detailProduct.image);$('#detailImage').alt=detailProduct.name;$('#detailCategory').innerHTML=`<i></i> ${safeText(detailProduct.category)}`;$('#detailName').textContent=detailProduct.name;$('#detailPrice').textContent=money(detailProduct.price);$('#detailDescription').textContent=detailProduct.description;$('#sizeOptions').innerHTML=(detailProduct.sizes||['Único']).map(s=>`<button class="size-option ${s===selectedSize?'selected':''}" data-size="${safeText(s)}">${safeText(s)}</button>`).join('');openPanel($('#productModal'))}
function addToCart(id,size='M'){const p=products.find(x=>x.id===id);if(!p)return;const count=cart.filter(x=>x.id===id).reduce((sum,x)=>sum+x.qty,0);if(Number.isFinite(p.stock)&&count>=p.stock){toast('Estoque indisponível para esta peça');return}const existing=cart.find(x=>x.id===id&&x.size===size);if(existing)existing.qty++;else cart.push({id,size,qty:1});saveStorage();renderCart();toast(`${p.name} foi para a sacola`)}
function countCart(){return cart.reduce((sum,item)=>sum+item.qty,0)}function cartTotal(){return cart.reduce((sum,item)=>sum+(products.find(p=>p.id===item.id)?.price||0)*item.qty,0)}
function renderCart(){const count=countCart();$('#cartCount').textContent=count;$('#drawerCount').textContent=`(${count})`;$('#cartEmpty').classList.toggle('hidden',count>0);$('#cartBottom').classList.toggle('hidden',!count);$('#cartItems').innerHTML=cart.map(item=>{const p=products.find(x=>x.id===item.id);if(!p)return'';const size=safeText(item.size);return `<div class="cart-item"><img src="${imageSrc(p.image)}" alt=""><div><h4>${safeText(p.name)}</h4><small>Tamanho ${size}</small><div class="quantity-control"><button data-qty="${p.id}|${size}|-1" aria-label="Diminuir">−</button><span>${item.qty}</span><button data-qty="${p.id}|${size}|1" aria-label="Aumentar">+</button><button class="remove-item" data-remove="${p.id}|${size}">Remover</button></div></div><span class="cart-item-price">${money(p.price*item.qty)}</span></div>`}).join('');$('#cartSubtotal').textContent=money(cartTotal())}
function setQuantity(id,size,delta){const item=cart.find(x=>x.id===id&&x.size===size);if(!item)return;item.qty+=delta;if(item.qty<1)cart=cart.filter(x=>x!==item);saveStorage();renderCart();renderCheckoutSummary()}
function removeItem(id,size){cart=cart.filter(x=>!(x.id===id&&x.size===size));saveStorage();renderCart();renderCheckoutSummary()}
const overlay=$('#overlay'),cartDrawer=$('#cartDrawer'),checkoutModal=$('#checkoutModal'),productModal=$('#productModal');
function openPanel(panel){overlay.classList.add('visible');panel.classList.add('open');panel.setAttribute('aria-hidden','false');document.body.style.overflow='hidden'}
function closePanel(panel){panel.classList.remove('open');panel.setAttribute('aria-hidden','true');if(!document.querySelector('.cart-drawer.open,.checkout-modal.open,.product-modal.open')){overlay.classList.remove('visible');document.body.style.overflow=''}}
function closeAll(){[cartDrawer,checkoutModal,productModal].forEach(p=>{p.classList.remove('open');p.setAttribute('aria-hidden','true')});overlay.classList.remove('visible');document.body.style.overflow=''}
function openCheckout(){if(!cart.length){toast('Sua sacola está vazia');return}closePanel(cartDrawer);$('#checkoutForm').classList.remove('hidden');$('#orderSuccess').classList.add('hidden');shippingFee=null;quotedAddress=null;$('#freightResult').textContent='';$('#addressResult').textContent='';openPanel(checkoutModal);renderCheckoutSummary()}
function selectedFulfillment(){return document.querySelector('input[name="fulfillment"]:checked')?.value||'pickup'}
function renderCheckoutSummary(){const target=$('#checkoutSummary');if(!target)return;target.innerHTML=cart.map(item=>{const p=products.find(x=>x.id===item.id);return `<div class="summary-line"><span>${item.qty} × ${p.name} · tam. ${item.size}</span><b>${money(p.price*item.qty)}</b></div>`}).join('');const fee=selectedFulfillment()==='delivery'?(shippingFee??0):0;$('#checkoutTotal').textContent=money(cartTotal()+fee)}
function updateChoiceStyles(){document.querySelectorAll('.choice-card').forEach(el=>el.classList.toggle('selected',el.querySelector('input').checked));document.querySelectorAll('.payment-option').forEach(el=>el.classList.toggle('selected',el.querySelector('input').checked));$('#deliveryFields').classList.toggle('hidden',selectedFulfillment()!=='delivery');renderCheckoutSummary()}
const freightByUf={SE:14,AL:23,BA:24,CE:26,MA:29,PB:25,PE:24,PI:29,RN:27,AC:42,AP:43,AM:40,PA:36,RO:36,RR:46,TO:32,DF:31,GO:31,MT:36,MS:31,ES:27,MG:28,RJ:27,SP:28,PR:31,RS:35,SC:32};
async function quoteShipping(){const raw=$('#cepInput').value.replace(/\D/g,'');if(raw.length!==8){toast('Digite um CEP com 8 números');return}const button=$('#quoteShipping');button.disabled=true;button.textContent='Consultando…';$('#freightResult').textContent='';$('#addressResult').textContent='';try{const response=await fetch(`https://viacep.com.br/ws/${raw}/json/`);if(!response.ok)throw new Error('CEP indisponível');const address=await response.json();if(address.erro)throw new Error('CEP não encontrado');quotedAddress=address;const city=(address.localidade||'').toLocaleLowerCase('pt-BR'),uf=address.uf;let fee=freightByUf[uf]??38;if(city==='estância'||city==='estancia'){if((address.bairro||'').toLocaleLowerCase('pt-BR').includes('centro'))fee=0;else fee=14}shippingFee=fee;const place=[address.logradouro,address.bairro,address.localidade,uf].filter(Boolean).join(' · ');$('#addressResult').textContent=`${place} · CEP ${raw.slice(0,5)}-${raw.slice(5)}`;$('#freightResult').textContent=fee===0?'Entrega grátis confirmada para o Centro de Estância.':'Frete estimado para '+uf+': '+money(fee)+' · valor final a confirmar com a loja.';renderCheckoutSummary()}catch(error){shippingFee=null;quotedAddress=null;$('#addressResult').textContent=error.message==='Failed to fetch'?'Não foi possível consultar o CEP. Confira sua conexão e tente novamente.':error.message;$('#freightResult').textContent=''}finally{button.disabled=false;button.textContent='Calcular entrega'}}
function formatCep(value){let digits=value.replace(/\D/g,'').slice(0,8);return digits.length>5?`${digits.slice(0,5)}-${digits.slice(5)}`:digits}function phoneDigits(value){return value.replace(/\D/g,'')}
function placeOrder(){const name=$('#buyerName').value.trim(),phone=phoneDigits($('#buyerPhone').value);if(!name){$('#buyerName').focus();toast('Informe seu nome para continuar');return}if(phone.length<10){$('#buyerPhone').focus();toast('Confira o número de WhatsApp');return}if(!cart.length){toast('Sua sacola está vazia');closeAll();return}const delivery=selectedFulfillment()==='delivery';if(delivery&&(!quotedAddress||shippingFee===null)){toast('Calcule o frete pelo CEP para continuar');$('#cepInput').focus();return}if(delivery&&!$('#addressExtra').value.trim()){toast('Informe o número do endereço');$('#addressExtra').focus();return}const payment=document.querySelector('input[name="payment"]:checked').value;const lines=cart.map(item=>{const p=products.find(x=>x.id===item.id);return `• ${item.qty}x ${p.name} (tam. ${item.size}) — ${money(p.price*item.qty)}`});const destination=delivery?`Entrega: ${quotedAddress.logradouro||''} ${$('#addressExtra').value}, ${quotedAddress.bairro||''}, ${quotedAddress.localidade}/${quotedAddress.uf} — CEP ${quotedAddress.cep}. Frete estimado: ${money(shippingFee)}.`:'Retirada: Centro de Estância (confirmar endereço).';const total=cartTotal()+(delivery?shippingFee:0);const message=`Olá, Donna Maria! Quero confirmar este pedido:\n\n${lines.join('\n')}\n\nSubtotal demonstrativo: ${money(cartTotal())}\n${destination}\nTotal estimado: ${money(total)}\nPagamento escolhido: ${payment}\n\nNome: ${name}\nMeu WhatsApp: ${$('#buyerPhone').value}\n\nPode confirmar disponibilidade, valores e próximos passos?`;$('#whatsappOrder').href=`https://wa.me/5579996520909?text=${encodeURIComponent(message)}`;$('#checkoutForm').classList.add('hidden');$('#orderSuccess').classList.remove('hidden')}
productGrid.addEventListener('click',event=>{const favorite=event.target.closest('[data-favorite]');if(favorite){event.stopPropagation();toggleFavorite(favorite.dataset.favorite);return}const detail=event.target.closest('[data-detail]');if(detail){showProduct(detail.dataset.detail);return}const card=event.target.closest('[data-product]');if(card)showProduct(card.dataset.product)});
$('#sizeOptions').addEventListener('click',event=>{const button=event.target.closest('[data-size]');if(!button)return;selectedSize=button.dataset.size;document.querySelectorAll('.size-option').forEach(x=>x.classList.toggle('selected',x===button))});$('#detailAdd').addEventListener('click',()=>{if(!detailProduct)return;addToCart(detailProduct.id,selectedSize);closePanel(productModal)});
$('#categoryTabs').addEventListener('click',event=>{const button=event.target.closest('[data-category]');if(button)setCategory(button.dataset.category)});$('#activeFilters').addEventListener('click',()=>setCategory('Todos'));$('#sortSelect').addEventListener('change',event=>{sortMode=event.target.value;renderProducts()});$('#productSearch').addEventListener('input',event=>{searchTerm=event.target.value;renderProducts()});
$('#searchOpen').addEventListener('click',()=>{$('#searchBox').classList.toggle('open');if($('#searchBox').classList.contains('open'))$('#productSearch').focus()});$('#searchClose').addEventListener('click',()=>{$('#productSearch').value='';searchTerm='';$('#searchBox').classList.remove('open');renderProducts()});$('#favoritesShortcut').addEventListener('click',()=>{setCategory('Favoritos');$('#colecao').scrollIntoView({behavior:'smooth'})});document.querySelectorAll('[data-category-link]').forEach(link=>link.addEventListener('click',()=>setCategory(link.dataset.categoryLink)));
$('#cartOpen').addEventListener('click',()=>openPanel(cartDrawer));$('#checkoutOpen').addEventListener('click',openCheckout);$('#continueShopping').addEventListener('click',()=>closePanel(cartDrawer));$('#backToCart').addEventListener('click',()=>{closePanel(checkoutModal);openPanel(cartDrawer)});$('#cartItems').addEventListener('click',event=>{const qty=event.target.closest('[data-qty]');if(qty){const[id,size,delta]=qty.dataset.qty.split('|');setQuantity(id,size,Number(delta));return}const remove=event.target.closest('[data-remove]');if(remove){const[id,size]=remove.dataset.remove.split('|');removeItem(id,size)}});
document.querySelectorAll('input[name="fulfillment"],input[name="payment"]').forEach(input=>input.addEventListener('change',updateChoiceStyles));$('#quoteShipping').addEventListener('click',quoteShipping);$('#cepInput').addEventListener('input',event=>{event.target.value=formatCep(event.target.value);shippingFee=null;quotedAddress=null;$('#freightResult').textContent='';renderCheckoutSummary()});$('#buyerPhone').addEventListener('input',event=>{let d=phoneDigits(event.target.value).slice(0,11);if(d.length>10)event.target.value=`(${d.slice(0,2)}) ${d.slice(2,7)}-${d.slice(7)}`;else if(d.length>6)event.target.value=`(${d.slice(0,2)}) ${d.slice(2,6)}-${d.slice(6)}`;else if(d.length>2)event.target.value=`(${d.slice(0,2)}) ${d.slice(2)}`;else event.target.value=d});
$('#placeOrder').addEventListener('click',placeOrder);$('#finishOrder').addEventListener('click',()=>{closeAll();cart=[];saveStorage();renderCart();$('#checkoutForm').classList.remove('hidden');$('#orderSuccess').classList.add('hidden')});overlay.addEventListener('click',closeAll);document.querySelectorAll('[data-close]').forEach(button=>button.addEventListener('click',closeAll));document.addEventListener('keydown',event=>{if(event.key==='Escape')closeAll()});$('#menuToggle').addEventListener('click',()=>$('#mainNav').classList.toggle('open'));$('#mainNav').addEventListener('click',event=>{if(event.target.closest('a'))$('#mainNav').classList.remove('open')});
$('#whatsappOrder').addEventListener('click',()=>{const id=$('#whatsappOrder').dataset.orderId||`DM-${Date.now().toString(36).toUpperCase()}`;let orders=[];try{orders=JSON.parse(localStorage.getItem('donna-orders')||'[]')}catch{}if(!orders.some(order=>order.id===id)){const delivery=selectedFulfillment()==='delivery';orders.unshift({id,createdAt:new Date().toISOString(),name:$('#buyerName').value.trim(),phone:$('#buyerPhone').value,payment:document.querySelector('input[name="payment"]:checked').value,fulfillment:delivery?'Entrega':'Retirada',destination:delivery?`${quotedAddress?.logradouro||''} ${$('#addressExtra').value}, ${quotedAddress?.bairro||''}, ${quotedAddress?.localidade||''}/${quotedAddress?.uf||''} · CEP ${quotedAddress?.cep||''}`:'Centro de Estância (confirmar endereço)',total:cartTotal()+(delivery?(shippingFee||0):0),status:'Novo',items:cart.map(item=>{const p=products.find(x=>x.id===item.id);return{id:item.id,name:p.name,size:item.size,qty:item.qty,price:p.price,image:p.image}})});try{localStorage.setItem('donna-orders',JSON.stringify(orders))}catch{}}});
renderProducts();renderCart();updateChoiceStyles();
window.addEventListener('storage',event=>{if(event.key==='donna-products'){products=window.DonnaCatalog.load();renderProducts();renderCart()}});
