const catalog=window.DonnaCatalog;
let products=catalog.load(),orders=loadOrders(),orderFilter='Todos';
const $=selector=>document.querySelector(selector),money=value=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(Number(value)||0);
const esc=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
const imageUrl=image=>/^data:image\//i.test(String(image||''))?image:`assets/${image}`;
function loadOrders(){try{const value=JSON.parse(localStorage.getItem('donna-orders')||'[]');return Array.isArray(value)?value:[]}catch{return[]}}
function saveOrders(){try{localStorage.setItem('donna-orders',JSON.stringify(orders))}catch{}}
function notify(message){$('#formMessage').textContent=message;setTimeout(()=>{$('#formMessage').textContent=''},2800)}
function updateMetrics(){products=catalog.load();orders=loadOrders();$('#metricOrders').textContent=orders.length;$('#ordersTabCount').textContent=orders.length;$('#metricProducts').textContent=products.length;$('#metricLowStock').textContent=products.filter(p=>Number.isFinite(p.stock)&&p.stock<=3).length}
function niceDate(value){const date=new Date(value);if(Number.isNaN(+date))return 'Data não informada';return new Intl.DateTimeFormat('pt-BR',{dateStyle:'medium',timeStyle:'short'}).format(date)}
function renderOrders(){orders=loadOrders();const search=$('#orderSearch').value.trim().toLowerCase();const filtered=orders.filter(order=>(orderFilter==='Todos'||(orderFilter==='Novo'?['Novo','Aguardando WhatsApp'].includes(order.status):orderFilter==='Em preparo'?['Confirmado','Em preparo','Enviado'].includes(order.status):order.status==='Concluído'))&&(!search||`${order.id} ${order.name} ${order.phone}`.toLowerCase().includes(search)));if(!filtered.length){$('#ordersList').innerHTML=$('#emptyOrdersTemplate').innerHTML;return}$('#ordersList').innerHTML=filtered.map(order=>{const items=(order.items||[]).map(item=>`${item.qty||1} × ${esc(item.name)} · ${esc(item.size||'—')}`).join('<br>');const phone=String(order.phone||'').replace(/\D/g,'');const statusOptions=['Novo','Confirmado','Em preparo','Enviado','Concluído','Cancelado'].map(status=>`<option ${order.status===status?'selected':''}>${status}</option>`).join('');return `<article class="order-card" data-order="${esc(order.id)}"><div><div class="order-id">${esc(order.id)}</div><div class="order-date">${esc(niceDate(order.createdAt))}</div><div class="order-total">${money(order.total)}</div></div><div class="order-detail"><div class="order-customer">${esc(order.name)} · ${esc(order.fulfillment||'')}</div><div class="order-meta">${esc(order.phone||'')}<br>Pagamento: ${esc(order.payment||'')}<br>${esc(order.destination||'')}</div><div class="order-items">${items}</div></div><div class="order-controls"><select data-order-status="${esc(order.id)}" aria-label="Status do pedido ${esc(order.id)}">${statusOptions}</select>${phone?`<a href="https://wa.me/${phone}" target="_blank" rel="noreferrer">Abrir WhatsApp ↗</a>`:''}</div></article>`}).join('')}
function stockLabel(stock){if(!Number.isFinite(stock))return ['Sem registro',''];if(stock===0)return ['Esgotado','out'];if(stock<=3)return [`${stock} un. · baixo`,'low'];return [`${stock} un. · disponível`,'']}
function renderProducts(){products=catalog.load();const search=$('#productSearchAdmin').value.trim().toLowerCase();const visible=products.filter(p=>`${p.name} ${p.category}`.toLowerCase().includes(search));if(!visible.length){$('#inventoryList').innerHTML='<div class="inventory-empty">Nenhum produto encontrado.</div>';return}$('#inventoryList').innerHTML=visible.map(p=>{const[caption,state]=stockLabel(p.stock);return `<article class="inventory-row" data-product-row="${esc(p.id)}"><img src="${esc(imageUrl(p.image))}" alt=""><div><div class="inventory-product-name">${esc(p.name)}</div><div class="inventory-category">${esc(p.category)} · ${(p.sizes||[]).map(esc).join(', ')}</div></div><div class="inventory-price">${money(p.price)}</div><label>Estoque<input class="stock-input" data-stock="${esc(p.id)}" type="number" min="0" step="1" value="${Number.isFinite(p.stock)?p.stock:''}" placeholder="—" aria-label="Estoque ${esc(p.name)}"><span class="stock-status ${state}">${caption}</span></label><button type="button" class="remove-product" data-remove-product="${esc(p.id)}">Excluir</button></article>`}).join('')}
function render(){updateMetrics();renderOrders();renderProducts()}
function setTab(name){document.querySelectorAll('.admin-tab').forEach(button=>button.classList.toggle('active',button.dataset.tab===name));$('#panel-orders').classList.toggle('hidden',name!=='orders');$('#panel-products').classList.toggle('hidden',name!=='products')}
function deductStock(order){products=catalog.load();for(const item of order.items||[]){const product=products.find(p=>p.id===item.id);if(product&&Number.isFinite(product.stock))product.stock=Math.max(0,product.stock-(Number(item.qty)||1))}catalog.save(products);order.stockDeducted=true}
function restoreStock(order){products=catalog.load();for(const item of order.items||[]){const product=products.find(p=>p.id===item.id);if(product&&Number.isFinite(product.stock))product.stock+=(Number(item.qty)||1)}catalog.save(products);order.stockDeducted=false}
function updateOrderStatus(id,status){orders=loadOrders();const order=orders.find(item=>item.id===id);if(!order)return;if(status==='Confirmado'&&!order.stockDeducted)deductStock(order);if(status==='Cancelado'&&order.stockDeducted)restoreStock(order);order.status=status;saveOrders();render()}
function makeSlug(text){return text.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')}
async function imageToDataUrl(file){if(!file)return '';if(file.size>12*1024*1024)throw new Error('Escolha uma foto menor que 12 MB.');const data=await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=()=>reject(new Error('Não foi possível ler a foto.'));reader.readAsDataURL(file)});const img=await new Promise((resolve,reject)=>{const element=new Image();element.onload=()=>resolve(element);element.onerror=()=>reject(new Error('Formato de imagem inválido.'));element.src=data});const scale=Math.min(1,1200/Math.max(img.width,img.height));const canvas=document.createElement('canvas');canvas.width=Math.round(img.width*scale);canvas.height=Math.round(img.height*scale);canvas.getContext('2d').drawImage(img,0,0,canvas.width,canvas.height);return canvas.toDataURL('image/jpeg',.82)}
function addProduct(product){products=catalog.load();product.id=`${makeSlug(product.name)||'produto'}-${Date.now().toString(36)}`;products.unshift(product);catalog.save(products);render();setTab('products')}

$('#todayDate').textContent=new Intl.DateTimeFormat('pt-BR',{dateStyle:'full'}).format(new Date());
document.querySelectorAll('[data-tab]').forEach(button=>button.addEventListener('click',()=>setTab(button.dataset.tab)));
document.querySelectorAll('[data-order-filter]').forEach(button=>button.addEventListener('click',()=>{orderFilter=button.dataset.orderFilter;document.querySelectorAll('[data-order-filter]').forEach(tab=>tab.classList.toggle('active',tab===button));renderOrders()}));
$('#orderSearch').addEventListener('input',renderOrders);$('#productSearchAdmin').addEventListener('input',renderProducts);
$('#ordersList').addEventListener('change',event=>{const select=event.target.closest('[data-order-status]');if(select)updateOrderStatus(select.dataset.orderStatus,select.value)});
$('#inventoryList').addEventListener('change',event=>{const input=event.target.closest('[data-stock]');if(!input)return;const value=input.value.trim()===''?null:Number(input.value);if(value!==null&&(!Number.isInteger(value)||value<0)){input.focus();return}products=catalog.load();const product=products.find(item=>item.id===input.dataset.stock);if(!product)return;if(value===null)delete product.stock;else product.stock=value;catalog.save(products);render();setTab('products')});
$('#inventoryList').addEventListener('click',event=>{const button=event.target.closest('[data-remove-product]');if(!button)return;const product=products.find(item=>item.id===button.dataset.removeProduct);if(!product||!window.confirm(`Excluir “${product.name}” do catálogo?`))return;products=catalog.load().filter(item=>item.id!==product.id);catalog.save(products);render()});
$('#toggleProductForm').addEventListener('click',()=>{$('#newProductForm').classList.toggle('hidden');$('#newProductForm').scrollIntoView({behavior:'smooth',block:'center'})});$('#closeProductForm').addEventListener('click',()=>$('#newProductForm').classList.add('hidden'));
$('#newProductForm').addEventListener('submit',async event=>{event.preventDefault();const form=event.currentTarget,values=new FormData(form),imageFile=values.get('image'),price=Number(values.get('price')),stock=Number(values.get('stock'));if(!imageFile||!imageFile.size){notify('Adicione uma foto para o produto.');return}if(!Number.isFinite(price)||price<=0||!Number.isInteger(stock)||stock<0){notify('Confira preço e quantidade em estoque.');return}const saveButton=form.querySelector('[type=submit]');saveButton.disabled=true;saveButton.textContent='Salvando…';try{const image=await imageToDataUrl(imageFile);addProduct({name:String(values.get('name')).trim(),category:String(values.get('category')),price,stock,sizes:String(values.get('sizes')).split(',').map(size=>size.trim()).filter(Boolean),description:String(values.get('description')||'').trim(),image,tag:'Novidade'});form.reset();form.classList.add('hidden');notify('Produto adicionado ao catálogo.')}catch(error){notify(error.message||'Não foi possível salvar este produto.')}finally{saveButton.disabled=false;saveButton.textContent='Salvar produto'}});
window.addEventListener('storage',event=>{if(event.key==='donna-products'||event.key==='donna-orders')render()});
render();
